using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel;

using Microsoft.VisualStudio.TestTools.WebTesting;
using Newtonsoft.Json.Linq;


namespace NorthwindAPI.Tests
{
    [DisplayName("Extract JSON rule")]
    [Description("Custom extraction rule for extracting values from JSON web response generated by web performance test")]
    public class JsonExtractionRule : ExtractionRule
    {
        public String Token { get; set; }
        public override void Extract(object sender, ExtractionEventArgs e)
        {
            var jsonString = e.Response.BodyString;
            var json = JObject.Parse(jsonString);
            JToken jToken = null;
            if (json == null)
            {
                e.Success = false;
                e.Message = "Response received not in JSON format";
            }
            else
            {
                jToken = json.SelectToken(Token);
                if (jToken == null){
                    e.Success = false;
                    e.Message = String.Format("{0} : Not found", Token);
                }
                else
                {
                    e.Success = true;
                    e.WebTest.Context.Add(this.ContextParameterName, jToken);
                }
            }
        }
    }
}
